# Generated by Django 2.0.2 on 2018-02-23 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.SlugField()),
                ('hologram_id', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.SlugField()),
                ('site', models.SlugField()),
                ('label', models.SlugField()),
                ('cal_m', models.FloatField(blank=True, null=True)),
                ('cal_b', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('seq', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datalogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datalogger.Datalogger')),
            ],
            options={
                'ordering': ['client', 'site', 'label'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('datalogger', 'seq'), ('client', 'site', 'label')},
        ),
    ]
