# Generated by Django 2.0.9 on 2018-11-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0002_auto_20180914_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
