# Generated by Django 2.0.9 on 2018-11-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0003_sensor_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalogger',
            name='hologram_id',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='sn',
            field=models.SlugField(unique=True),
        ),
    ]
