# Generated by Django 2.0.9 on 2018-11-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0004_auto_20181116_0328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['-active', 'client', 'site', 'label']},
        ),
    ]
